name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    #Firebase
  firebase_core: ^1.19.2
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^2.5.1
  fluttertoast: ^8.0.8
  smooth_page_indicator: ^1.0.0+2
  lottie: ^1.3.0
  firebase_messaging: ^12.0.0
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.3+1
  path_provider: ^2.0.1
  flutter_phone_direct_caller: ^2.0.0
  url_launcher: ^6.0.9
  flutter_sms: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this: 
  assets:
    - img/img.jpg
    - assets/logo.png
    - img/medicine.png
    - img/amb.png
    - img/hosi.png
    - img/grocy.png
    - assets/cookiechoco.jpg
    - assets/cookieclassic.jpg
    - assets/cookiemint.jpg
    - assets/cookievan.jpg
    - img/coviself.jpeg
    - img/limcee.jpeg
    - img/zinco.jpeg
    - img/steam.jpeg
    - img/cofsils.jpeg
    - img/hand.jpeg
    - img/thermo.jpeg
    - img/ash.jpeg
    - img/brahmi.jpeg
    - img/vita.jpeg
    - img/health.jpeg
    - img/medha.jpeg
    - img/oil.jpeg
    - img/sleep.jpeg
    - img/olive.jpeg
    - img/liver.jpeg
    - img/omega.jpeg
    - img/bp.jpeg
    - img/tulsi.jpeg
    - img/mcg.jpeg
    - img/ant.jpeg
    - img/tooth.jpeg
    - img/cleaner.jpeg
    - img/mouth.jpeg
    - img/brush.jpeg
    - img/spray.jpeg
    - img/floss.jpeg
    - img/gel.jpeg
    - img/back.jpeg
    - img/moov.jpeg
    - img/headache.jpeg
    - img/zandu.jpeg
    - img/vapour.jpeg
    - img/disprin.jpeg
    - img/hot.jpeg
    - img/ice.jpeg
    - img/booster.jpeg
    - img/honey.jpeg
    - img/karela.jpeg
    - img/aloe.jpeg
    - img/women.jpeg
    - img/amla.jpeg
    - img/jeera.jpeg
    - img/gaviscon.jpeg
    - img/acid.jpeg
    - img/syrup.jpeg
    - img/blood.jpeg
    - img/pudin.jpeg
    - img/eno.jpeg
    - img/qr.jpeg
    - img/logo.jpeg
    # - img/.jpeg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
